#!/bin/bash
set -x

# 更换yum源
cd /etc/yum.repos.d
mv CentOS-Base.repo CentOS-Base.repo.bak
wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
yum makecache

# 下载安装包
yum install -y wget squid openssl openssl-devel lzo lzo-devel pam pam-devel automake pkgconfig openvpn git httpd


# 清理环境
squid -k kill
httpd -k stop
pkill -9 openvpn

# 下载配置及模板
rm -rf /container-vpn
cd /
git clone https://github.com/helloworldppp/container-vpn.git
cd /container-vpn
chmod +x genovpn.py start

# 生成证书
cd /container-vpn/easy-rsa
sh ./build-all

rm -rf /etc/openvpn/keys
cp -r keys /etc/openvpn/keys

# copy 证书
rm -rf /etc/openvpn/openvpn.conf
rm -rf /etc/squid/squid.conf
cp /container-vpn/conf/openvpn.conf /etc/openvpn/
cp /container-vpn/conf/squid.conf /etc/squid/

# 生成ovpn模板
cd /container-vpn/
rm -rf /var/www/html/*
mkdir /var/www/html/file
./genovpn.py > /tmp/ovpnurl


# 修改启动脚本
if [ ! -f /container-vpn/entrypoint.sh ]; then
	cp /entrypoint.sh /container-vpn/
fi
sed 's#exec $@#/container-vpn/start#' /container-vpn/entrypoint.sh > /entrypoint.sh

# 启动服务
echo "Service started. Download ovpn from:"
cat /tmp/ovpnurl

/container-vpn/start